Aide_Text_HaventCaughtEnoughMonsForItem::
	.string "Vamos ver…\n"
	.string "Ops! Você capturou apenas\l"
	.string "{STR_VAR_3} tipos de POKéMON!\p"
	.string "Você precisa de {STR_VAR_1} tipos\n"
	.string "se quiser o {STR_VAR_2}.$"

Aide_Text_GetEnoughMonsComeBackForItem::
	.string "...\n"
	.string "Entendo.\p"
	.string "Quando conseguir {STR_VAR_1} tipos de POKéMON,\n"
	.string "volte para pegar o {STR_VAR_2}.$"

Aide_Text_DontHaveAnyRoomForItem::
	.string "Ah! Vejo que você não tem\n"
	.string "espaço para o {STR_VAR_2}.$"
