gOtherText_NewName::
    .string "NOVO NOME$"

gNameChoice_Green::
    .string "GREEN$"

gNameChoice_Red::
    .string "RED$"

gNameChoice_Leaf::
    .string "LEAF$"

gNameChoice_Fire::
    .string "FIRE$"

gNameChoice_Gary::
    .string "GARY$"

gNameChoice_Kaz::
    .string "KAZ$"

gNameChoice_Toru::
    .string "TORU$"

gNameChoice_Ash::
    .string "ASH$"

gNameChoice_Kene::
    .string "KENE$"

gNameChoice_Geki::
    .string "GEKI$"

gNameChoice_Jak::
    .string "JAK$"

gNameChoice_Janne::
    .string "JANNE$"

gNameChoice_Jonn::
    .string "JONN$"

gNameChoice_Kamon::
    .string "KAMON$"

gNameChoice_Karl::
    .string "KARL$"

gNameChoice_Taylor::
    .string "TAYLOR$"

gNameChoice_Oscar::
    .string "OSCAR$"

gNameChoice_Hiro::
    .string "HIRO$"

gNameChoice_Max::
    .string "MAX$"

gNameChoice_Jon::
    .string "JON$"

gNameChoice_Ralph::
    .string "RALPH$"

gNameChoice_Kay::
    .string "KAY$"

gNameChoice_Tosh::
    .string "TOSH$"

gNameChoice_Roak::
    .string "ROAK$"

gNameChoice_Omi::
    .string "OMI$"

gNameChoice_Jodi::
    .string "JODI$"

gNameChoice_Amanda::
    .string "AMANDA$"

gNameChoice_Hillary::
    .string "HILLARY$"

gNameChoice_Makey::
    .string "MAKEY$"

gNameChoice_Michi::
    .string "MICHI$"

gNameChoice_Paula::
    .string "PAULA$"

gNameChoice_June::
    .string "JUNE$"

gNameChoice_Cassie::
    .string "CASSIE$"

gNameChoice_Rey::
    .string "REY$"

gNameChoice_Seda::
    .string "SEDA$"

gNameChoice_Kiko::
    .string "KIKO$"

gNameChoice_Mina::
    .string "MINA$"

gNameChoice_Norie::
    .string "NORIE$"

gNameChoice_Sai::
    .string "SAI$"

gNameChoice_Momo::
    .string "MOMO$"

gNameChoice_Suzi::
    .string "SUZI$"

gControlsGuide_Text_Intro::
.string "Os botões serão explicados na\n"
.string "ordem de sua importância.$"

gControlsGuide_Text_DPad::
.string "Move o personagem principal.\n"
.string "Também usado para escolher vários\n"
.string "tópicos de dados.$"

gControlsGuide_Text_AButton::
.string "Usado para confirmar uma escolha,\n"
.string "examinar coisas e rolar o texto.$"

gControlsGuide_Text_BButton::
.string "Usado pra sair, cancelar uma\n"
.string "escolha e cancelar um modo.$"

gControlsGuide_Text_StartButton::
.string "Pressione para abrir o MENU.$"

gControlsGuide_Text_SelectButton::
.string "Move itens e usa um item\n"
.string "registrado.$"

gControlsGuide_Text_LRButtons::
.string "Para ajuda ou instruções de\n"
.string "como jogar, pressione L ou R.$"

gOakSpeech_Text_AskPlayerGender::
.string "Agora me diga. Você é um garoto?\n"
.string "Ou é uma garota?$"

gPikachuIntro_Text_Page1::
.string "No mundo em que vai entrar, você\n"
.string "terá uma grande aventura como herói.\n"
.string "\n"
.string "Fale com pessoas e examine tudo por\n"
.string "onde passar. Colete dicas.$"

gPikachuIntro_Text_Page2::
.string "Novos caminhos se abrirão ao ajudar\n"
.string "pessoas, superar desafios e desvendar\n"
.string "mistérios.\n"
.string "\n"
.string "Às vezes, será desafiado por outros\n"
.string "e atacado por criaturas selvagens.\n"
.string "Seja corajoso e siga em frente.$"

gPikachuIntro_Text_Page3::
.string "Esperamos que você interaja com\n"
.string "muitas pessoas e cresça com sua\n"
.string "jornada. Esse é nosso maior objetivo.\n"
.string "\n"
.string "Pressione o Botão A e deixe sua\n"
.string "aventura começar!$"

gOakSpeech_Text_WelcomeToTheWorld::
.string "Olá!\n"
.string "Prazer em conhecê-lo!\p"
.string "Bem-vindo ao mundo dos POKéMON!\p"
.string "Meu nome é OAK.\p"
.string "As pessoas carinhosamente me chamam\n"
.string "de PROFESSOR POKéMON.\p$"

gOakSpeech_Text_ThisWorld::
.string "Este mundo...$"

gOakSpeech_Text_IsInhabitedFarAndWide::
.string "...é habitado por toda parte por\n"
.string "criaturas chamadas POKéMON.\p$"

gOakSpeech_Text_IStudyPokemon::
.string "Para alguns, POKéMON são pets.\n"
.string "Outros os usam para batalhas.\p"
.string "Quanto a mim...\p"
.string "Eu estudo POKéMON como profissão.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
.string "Mas primeiro, me fale um pouco\n"
.string "sobre você.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
.string "Vamos começar com o seu nome.\n"
.string "Qual é?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
.string "Certo...\n"
.string "Então seu nome é {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
.string "Este é meu neto.\p"
.string "Ele tem sido seu rival desde que\n"
.string "vocês eram bebês.\p"
.string "...Erm, qual era o nome dele mesmo?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
.string "O nome do seu rival, qual era mesmo?$"

gOakSpeech_Text_ConfirmRivalName::
.string "...Er, era {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
.string "Isso mesmo! Me lembrei agora!\n"
.string "O nome dele é {RIVAL}!\p$"

gOakSpeech_Text_LetsGo::
.string "{PLAYER}!\p"
.string "Sua própria lenda dos POKéMON\n"
.string "está prestes a se desenrolar!\p"
.string "Um mundo de sonhos e aventuras\n"
.string "com POKéMON aguarda! Vamos lá!$"
